In [2]:
import psycopg2

try:
    conn = psycopg2.connect(
        dbname="mi_bd",
        user="jhan",
        password="1234",
        host="localhost",
        port="5432"
    )

    print("✅ CONEXIÓN EXITOSA A POSTGRES")

    conn.close()

except Exception as e:
    print("❌ ERROR DE CONEXIÓN:", e)

✅ CONEXIÓN EXITOSA A POSTGRES

In [4]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://jhan:1234@localhost:5432/mi_bd"
)

try:
    conn = engine.connect()
    print("✅ CONEXIÓN SQLALCHEMY EXITOSA")
    conn.close()

except Exception as e:
    print("❌ ERROR:", e)

✅ CONEXIÓN SQLALCHEMY EXITOSA

In [6]:
import pandas as pd

# Cargar dataset
df = pd.read_csv('../data/online_retail.csv', encoding='ISO-8859-1')

# Vista rápida
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [8]:
df_clean = df.copy()

In [9]:
df_clean.columns = df_clean.columns.str.lower()

In [10]:
df_clean.head()

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom